-------------------------------------------------
-- Filename:        maria_db.sql
-- Version:         0.0.1
-- Release Date:    ../../....
-- Description:     ...
-- Notes:           ...
--
-- Public License: CC-BY-NC-SA 4.0 International License
--   http://creativecommons.org/licenses/by-nc-sa/4.0/
--
-- Commercial License Agreement: All commercial rights are reserved by ...
--   https://github.com/GHNewbiee/etma/blob/master/COMMERCIAL_LICENSE_AGREEMENT.md
--
-- Author(s): ...
-- Major contributor(s): ...
--
-- Αcknowledg(e)ment: MariaDB, ...

-- Bug report and new feature request:
--   https://github.com/GHNewbiee/etma/blob/master/.github/CONTRIBUTING.md
-- General or HowTo question:
-- ...
-------------------------------------------------

